name: PR Build Test

on:
  pull_request:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v6

      - uses: actions/checkout@v6
        with:
          repository: frappe/frappe_docker
          path: frappe_docker

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Generate apps.json
        run: python .github/scripts/render_apps_json.py

      - uses: docker/setup-buildx-action@v3

      - name: Build only
        uses: docker/build-push-action@v6
        with:
          context: frappe_docker
          file: frappe_docker/images/custom/Containerfile
          push: false
          build-args: |
            APPS_JSON_BASE64=${{ env.APPS_JSON_BASE64 }}

